### ISSUE TITLE
`color_range` not working properly

### ISSUE THREAD

**Issue by liuzhenqi77** [danjgale/surfplot#18]
## Summary

Colors are not following the colorbar, and `color_range` is not working properly. 
(Plotting the same data using brainspace gives different results.)

## Reproducing the bug

Plotting the same data using brainspace

```python
import numpy as np
import surfplot
from brainspace.plotting import plot_hemispheres
from brainspace.datasets import load_parcellation
from brainspace.utils.parcellation import map_to_labels
from brainspace.datasets import load_conte69

test_data = np.random.normal(0, 0.2, (400,))

labeling = load_parcellation('schaefer', scale=400, join=True)
surf_lh, surf_rh = load_conte69()
mapped_data = map_to_labels(test_data, labeling, mask=labeling != 0, fill=np.nan)

# surfplot
p = surfplot.Plot(surf_lh=surf_lh, surf_rh=surf_rh)
p.add_layer(mapped_data, zero_transparent=False, cbar=True, cmap="RdBu_r") # try setting color_range
fig = p.build()

# brainspace
plot_hemispheres(surf_lh, surf_rh, array_name=mapped_data, size=(1200, 400), cmap='RdBu_r', embed_nb=True, color_bar=True)

```

## Additional details

After some debugging, I think the problem is caused by this passed parameter [`share=True`](https://github.com/danjgale/surfplot/blob/11e959e2faefa1acb5c1f19835affc18bbce144b/surfplot/plotting.py#L395). Changing it to `False` seems to fix the problem (at least giving the same looking figure as brainspace).

Because `surfplot.plotting.Plot` has a [default gray surface with `color_range=(0, 1)`](https://github.com/danjgale/surfplot/blob/11e959e2faefa1acb5c1f19835affc18bbce144b/surfplot/plotting.py#L253). When the color ranges are passed to `brainspace.plotting.utils._get_ranges`, which does not handle the layers --- it would be affected by range of `(0, 1)`. I haven't tested but this might also affect figure with multiple layers in different scales.

**Comment by danjgale** [comment]
Hi @liuzhenqi77, 

Thanks for your issue! However, I'm not sure I follow. Using your provided code, I truncated the color range by setting `color_range=(-.3, .3)` in both the surfplot and brainspace figures. This resulted in the following (top: brainspace, bottom: surfplot):

![image](https://user-images.githubusercontent.com/14634382/192564563-b2059550-47b5-4826-8f88-ad78c7a9e961.png)

Of course, the color of the medial wall is different between the two, but the data looks to be plotted the same.

**Comment by liuzhenqi77** [comment]
Thanks for the reply! I checked again with a clean conda install (vtk==9.1.0, matplotlib=3.5.2, brainspace and surfplot from github main branch), however, the problem is still there. I'm confused.

Could you use the latest versions and check the result of [`spec` before and after `_get_ranges`](https://github.com/danjgale/surfplot/blob/11e959e2faefa1acb5c1f19835affc18bbce144b/surfplot/surf.py#L229)? It seems to me different layers in surfplot were treated as one for `color_range` when [share=True](https://github.com/danjgale/surfplot/blob/11e959e2faefa1acb5c1f19835affc18bbce144b/surfplot/plotting.py#L395).

![Figure_1](https://user-images.githubusercontent.com/7530936/192577430-a9e2a563-db6a-4a74-8fce-16ee3935771a.png)
![Figure_2](https://user-images.githubusercontent.com/7530936/192579568-bf751a8e-6280-46f0-ace9-33663c11dc36.png)

**Comment by liuzhenqi77** [comment]
Could it be caused by [this recent commit](https://github.com/MICA-MNI/BrainSpace/commit/44d55d3e52ce59ccb6b25a3767569b091960798e) from brainspace?

**Comment by danjgale** [comment]
That could very well be the culprit. I'll have to investigate further. In the meantime, the successful combinations of package versions that I use:

brainspace=0.1.1
matplotlib=3.4.2
vtk=9.0.1

This might provide a temporay solution for you until I update surfplot in the coming weeks.

**Comment by danjgale** [comment]
#19 should fix this. Thanks @liuzhenqi77!
