### ISSUE TITLE
Suggestion: more ROI outline methods

### ISSUE THREAD

**Issue by yusaiwen** [danjgale/surfplot#21]
Reference: https://github.com/StuartJO/plotSurfaceROIBoundary

I hope this could add to Surfplot, for Surfplot is really easy to use(with Brainspace and Neuromaps)!

Thanks.

**Comment by danjgale** [comment]
Thanks for this! That looks pretty interesting and I would have to take some time to figure out the implementation. What use-case are you envisioning for different boundary styles?
