### ISSUE TITLE
Issues using custom colormaps

### ISSUE THREAD

**Issue by elvisha** [danjgale/surfplot#22]
I'm having some issues visualising ROIs using custom colormaps. I've tried following this example (https://surfplot.readthedocs.io/en/latest/auto_examples/plot_tutorial_06.html) but I keep getting the following issue when I use a custom colormap - any idea what I might be doing wrong? 
Thanks! 

<img width="280" alt="Screenshot 2022-12-22 at 10 56 49" src="https://user-images.githubusercontent.com/51443986/209173046-ef3329bd-62dd-4ff2-9d8b-320245780789.png">

**Comment by elvisha** [comment]
Sorry, just found the relevant documentation to address this. Will give it a shot!

**Comment by danjgale** [comment]
Hey @elvisha let me know if you still run into issues! Updating surfplot to the latest version _should_ fix this issue

**Comment by elvisha** [comment]
Thanks! Ended up having to update to the latest version of surfplot and downgrading to matplotlib version 3.4.2 but got it to work now!
