### ISSUE TITLE
matplotlib not responding?

### ISSUE THREAD

**Issue by rtang2100** [danjgale/surfplot#24]
Hello,

Thank you for this wonderful tool! I would like to use it to plot surfaces, but it seems like I'm running into a road block before even starting the actual plotting....

I've updated my matplotlib package and have tried the following commands:
from neuromaps.datasets import [fetch_fsaverage](https://netneurolab.github.io/neuromaps/generated/neuromaps.datasets.fetch_fsaverage.html#neuromaps.datasets.fetch_fsaverage)
from surfplot import Plot

surfaces = [fetch_fsaverage](https://netneurolab.github.io/neuromaps/generated/neuromaps.datasets.fetch_fsaverage.html#neuromaps.datasets.fetch_fsaverage)(density='164k')
lh, rh = surfaces['inflated']

# make figure
p = Plot(lh, rh)
fig = p.build()
fig.show()

After the fig.show(), a matplotlib icon will show in my linux taskbar. However, if I clicked on it, it will show matplotlib is not responding, and I will have to force quit eventually. I have done some search of this issue online - for example, changing backend, but it still does not resolve my issue.

Thanks,
Catherine

**Comment by danjgale** [comment]
Hi @rtang2100, 

Sorry for the late response. Thanks for bringing this to my attention, were you able to resolve this or is this still an issue? If so, what version of matplotlib were/are you running?
